### PR TITLE
Implement the Automatic Classpath Detection

### PR DESCRIPTION
**Pull request by arksap2002**
# Description of changes made
The project path automatically sets after the test generation is started.

# Why is merge request needed
User should not set the path automatically.

# Other notes
Closes #ICTL-189

# What is missing?
1) Tests

### CODE REVIEW

**Comment by pderakhshanfar** [comment]
The path detection works correctly with a single-module project. However, if we want to apply TestGenie on larger projects, we will have more than one module, which means we have more than one directory with the compiled classes. I tried testGenie with another project of mine that has more than one module: botsing-commons, botsing-reproduction etc. (https://github.com/STAMP-project/botsing/tree/evosuite-update), and it only passes one incorrect directory (look at the screenshot). 
Screenshot 2023-02-17 at 14 58 41

Can you update the pathfinder script to search for all directories with the `.class` files?

**Comment by arksap2002** [comment]
> The path detection works correctly with a single-module project. However, if we want to apply TestGenie on larger projects, we will have more than one module, which means we have more than one directory with the compiled classes. I tried testGenie with another project of mine that has more than one module: botsing-commons, botsing-reproduction etc. (https://github.com/STAMP-project/botsing/tree/evosuite-update), and it only passes one incorrect directory (look at the screenshot). Screenshot 2023-02-17 at 14 58 41
> 
> Can you update the pathfinder script to search for all directories with the `.class` files?

thank you, fixed, could you check it, please :)

**Comment by pderakhshanfar** [comment]
It still does not work on the multi-module project. Line 260 of your `Pipeline.kt` class only detects the directory which has the compiled version of the class under test. However, if you have a module called `Project-commons` and you use this module in classes from another module (e.g., `Project-moduleA`). When you ask TestGenie to generate tests for a class in `Project-moduleA`, it needs the compiled classes from both modules `Project-moduleA` and `Project-commons`. In this scenario, the current implementation of the build pathfinder only returns the build path of `Project-moduleA`, which leads to EvoSuite's failure. 

I checked the documentation of IntelliJ, and I found a solution. Instead of manually searching for the `.class` files, you should first get list of modules by `ModuleManager.getInstance(project).modules`. Then, for each of the modules you can get the output directory by `CompilerModuleExtension.getInstance(module).compilerOutputPath`. Just keep in mind that `compilerOutputPath ` might return `null` for the modules without compile path. Make sure that you handle the `null` values. This should work for any type of project (Maven, Gradle, IntelliJ, etc.).

**Comment by arksap2002** [comment]
> It still does not work on the multi-module project. Line 260 of your `Pipeline.kt` class only detects the directory which has the compiled version of the class under test. However, if you have a module called `Project-commons` and you use this module in classes from another module (e.g., `Project-moduleA`). When you ask TestGenie to generate tests for a class in `Project-moduleA`, it needs the compiled classes from both modules `Project-moduleA` and `Project-commons`. In this scenario, the current implementation of the build pathfinder only returns the build path of `Project-moduleA`, which leads to EvoSuite's failure.
> 
> I checked the documentation of IntelliJ, and I found a solution. Instead of manually searching for the `.class` files, you should first get list of modules by `ModuleManager.getInstance(project).modules`. Then, for each of the modules you can get the output directory by `CompilerModuleExtension.getInstance(module).compilerOutputPath`. Just keep in mind that `compilerOutputPath ` might return `null` for the modules without compile path. Make sure that you handle the `null` values. This should work for any type of project (Maven, Gradle, IntelliJ, etc.).

thank you for review and helping this the way of the solution. I tried to solve this moment with looking for build path in IDEA, but I didn't find `CompilerModuleExtension`, added it to the code.

**Comment by arksap2002** [comment]
For future.
I think, that is it better to merge this PR after this one: https://github.com/JetBrains-Research/TestGenie/pull/14

**Pull request merged**
