### PR TITLE
Add automatically creating a file for tests

### PR DESCRIPTION
**Pull request by arksap2002**
# Description of changes made
At the moment, it is possible to put the generated tests only in existing files. The idea is to add the opportunity to create new ones.

# Why is merge request needed
To add the opportunity to create new file for tests.

# Other notes
Closes [ICTL-270](https://youtrack.jetbrains.com/issue/ICTL-270)

# What is missing?
1. Add package line to a new file
2. Add imports to a new file

### CODE REVIEW

**Comment by arksap2002** [comment]
Merge after merging this PR: https://github.com/JetBrains-Research/TestGenie/pull/17

**Comment by arksap2002** [comment]
> The window that opens after selecting `apply test` does not follow the selected theme in the dark mode (Look at the screenshot). Screenshot 2023-03-16 at 17 45 55

unfortunately, it seems, that this is the porblem with the `JFileChooser` design, because the theme of this window is the same with the IDEA theme. We can see the color changing after setting the white IDEA theme.
Screenshot 2023-03-19 at 23 12 35
Screenshot 2023-03-19 at 23 16 25

**Comment by pderakhshanfar** [comment]
Is `JFileChooser` our best option, then? Could you find better options in IntelliJ implementations? https://plugins.jetbrains.com/docs/intellij/file-and-class-choosers.html
In the current version, even some texts are black on a dark background, which makes them unreadable.

**Comment by arksap2002** [comment]
> Is `JFileChooser` our best option, then? Could you find better options in IntelliJ implementations? https://plugins.jetbrains.com/docs/intellij/file-and-class-choosers.html In the current version, even some texts are black on a dark background, which makes them unreadable.

I need to get from the user the folder in which he wants to create a new file. Unfortunately, all `File` and `Class` `Choosers` do not allow you to select them. `PackageChooser` seems like a great option, but I need to understand how to take the path from the `Psipackage`, or translate it into a file, or into `Psidirectory`, but I haven't found a good way for this. I can ask the user to enter the path by hand, but it is not good way, I think.

**Pull request merged**
